/**
 * The lesson content-type catalogue.
 *
 * CODE, not data — the fifth in this codebase after `permissions.ts`,
 * `badges.ts`, `workforce.ts` and `course-taxonomy.ts`. Here the reason is the
 * sharpest yet: each type carries its own **validation rule**, and a rule
 * cannot hang off a string an admin typed.
 *
 * WHAT EACH TYPE NEEDS, AND WHY THE RULES DIFFER
 *
 *   video   a file or a link. Duration OPTIONAL — a video reports its own
 *           runtime, and measured watch time is what counts until the lesson
 *           is complete (§10.4).
 *   pdf     ┐
 *   word    │ a file or a link. Duration MANDATORY: none of them has a
 *   ppt     │ runtime to measure, so a null duration silently makes the
 *   image   ┘ lesson worth zero learning hours.
 *   link    a URL only — there is nothing to upload. Duration MANDATORY, same
 *           reason.
 *   scorm   an uploaded package. Duration mandatory UNLESS the manifest
 *           declared one (§10.8); the service checks the package, not this
 *           table.
 *
 * `session` and `quiz` are NOT offered here. A session lesson is generated by
 * its session (§10.7) and the course editor refuses to touch it; a quiz is the
 * question set, reached through the Assessments tab. Both still exist in the
 * column — this list is what the lesson FORM may create.
 */

export interface LessonContentType {
  key: string;
  label: string;
  /** Can the admin upload a file for this, or is it link-only? */
  upload: boolean;
  /** Is a typed duration required? False only where a runtime is measurable. */
  durationRequired: boolean;
  /** Accept attribute for the file picker. Empty when `upload` is false. */
  accept: string;
  /** What the picker tells the admin. */
  hint: string;
}

/**
 * WORD AND POWERPOINT ARE DELIBERATELY ABSENT, and this is the one entry in
 * this file that is a product decision rather than a description.
 *
 * Course content is not meant to leave the product, so a lesson's primary
 * content must be something a BROWSER can render — only then can it be shown
 * without handing over the file. PDF, images and video all qualify. `.docx`
 * and `.pptx` do not: a browser's only move is to pass them to a desktop
 * application, which means a download. Offering them as protected lesson
 * content would have been a control that lies.
 *
 * Converting them to PDF server-side was considered and rejected. It would
 * work for a plain reference deck and would silently destroy a narrated one —
 * PDF has no audio, no animation and no timings, so a 20-minute voiced-over
 * deck becomes a stack of silent slides with every progressive reveal
 * collapsed on top of itself, and nothing on screen says anything was lost.
 *
 * What an admin should do instead is stated in the lesson form:
 *   narrated / animated deck -> PowerPoint's File > Export > Create a Video,
 *                               uploaded as a `video` lesson. Keeps the
 *                               voiceover, the animations and the timings,
 *                               AND earns measured watch time (§10.4) rather
 *                               than a duration somebody typed.
 *   plain reference deck     -> Save as PDF.
 *
 * Both remain perfectly valid as supporting RESOURCES (`lesson_resources`),
 * which are labelled as reference material, carry no duration and are not
 * the thing being protected.
 *
 * They stay in `DOCUMENT_LIKE_TYPES` below, so any row that already holds one
 * keeps rendering. Readable, not creatable — the same treatment the legacy
 * `document` / `doc` / `xls` values get.
 */
export const LESSON_CONTENT_TYPES: LessonContentType[] = [
  {
    key: 'video',
    label: 'Video',
    upload: true,
    durationRequired: false,
    accept: 'video/mp4,video/webm,video/quicktime,.mp4,.webm,.mov',
    hint: 'MP4, WebM or MOV',
  },
  {
    key: 'pdf',
    label: 'PDF',
    upload: true,
    durationRequired: true,
    accept: 'application/pdf,.pdf',
    hint: 'PDF only',
  },
  {
    key: 'image',
    label: 'Image',
    upload: true,
    durationRequired: true,
    accept: 'image/jpeg,image/png,image/gif,image/webp',
    hint: 'JPG, PNG, GIF or WebP',
  },
  {
    key: 'link',
    label: 'External link',
    upload: false,
    durationRequired: true,
    accept: '',
    hint: 'Opens in a new tab for the learner',
  },
  {
    key: 'scorm',
    label: 'SCORM package',
    upload: true,
    durationRequired: true,
    accept: 'application/zip,.zip',
    hint: 'SCORM 1.2 or 2004, as a .zip',
  },
];

/** Keys the lesson form may submit. */
export const LESSON_CONTENT_KEYS = LESSON_CONTENT_TYPES.map((t) => t.key);

/**
 * Types stored as a file in the document slot (`document_key`) or a link.
 *
 * `document` is the legacy value the old form wrote and `doc`/`xls` are older
 * still; they behave identically and are kept so existing rows stay valid.
 * They are absent from `LESSON_CONTENT_TYPES` on purpose — readable, not
 * creatable.
 */
export const DOCUMENT_LIKE_TYPES = new Set([
  'pdf', 'word', 'ppt', 'image',
  'document', 'doc', 'xls',
]);

export function isDocumentLike(contentType: string): boolean {
  return DOCUMENT_LIKE_TYPES.has((contentType || '').toLowerCase());
}

export function contentTypeOf(key: string): LessonContentType | undefined {
  return LESSON_CONTENT_TYPES.find((t) => t.key === key);
}

/**
 * Does this type need a typed duration?
 *
 * Unknown/legacy types answer true, which is the safe direction: §10.4 pays a
 * completed lesson its declared duration, and a null there is worth zero hours.
 */
export function durationRequiredFor(contentType: string): boolean {
  const type = contentTypeOf(contentType);
  if (type) return type.durationRequired;
  return contentType !== 'video' && contentType !== 'session';
}
